#Travis.yaml file for node.js
language: node_js
sudo: false
node_js:
  - 10
  - 9 
  - 8
  - 7

install:
  - npm install 
<<<<<<< HEAD
  
=======

>>>>>>> 662b839ef75c4961ea4c7f82f30c233d0f76c5e8
script:
  - npm test
